version:0.1
config-name:Default
storage-type:Filesystem
global-option:Image,alignment.image.stride:1
global-option:Image,image.data.address.alignment:4
global-option:Image,image.export.format:Native Format
global-option:Image,opaque.image.export.format:Global Image Format
global-option:Image,preview.background:#ffffff
global-option:Image,resource.declaration.postfix:
global-option:Image,resource.declaration.prefix:
global-option:Image Map,image.map.width:800
global-option:Font,bitmap.depth:8 Bit
global-option:Font,character.range:All Glyphs Found In Font
global-option:Font,font.export.format:TTF
global-option:Font,resource.declaration.postfix:
global-option:Font,resource.declaration.prefix:
global-option:Font Size,glyph.map.width:800
global-option:Model,generate.condensed.gapp.file:true
global-option:Model,generate.static.string.map:false
global-option:Model,resource.declaration.postfix:
global-option:Model,resource.declaration.prefix:
global-option:Script,resource.declaration.postfix:
global-option:Script,resource.declaration.prefix:
global-option:Script,script.export.format:Raw
global-option:Other,resource.declaration.postfix:
global-option:Other,resource.declaration.prefix:
images/green-button.png,Image,include.export:true
scripts/publish.lua,Script,include.export:true
scripts/subscribe.lua,Script,include.export:true
